version: "3.8"

name: "meetmephi"

networks:
  loki:

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=meetmephi
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '2900:2900'
    stdin_open: true
    tty: true
  backend:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    container_name: backend
    ports:
      - '8000:8000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/meetmephi
      - JWT_KEY=ojnbfgklvmdfpvmoiedrfvnmwerkcvmweocvnrewmviernvuijdfvedrfmvoidfgnbfgmbfgmbufgnbo
  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki


