version: "3.8"

name: "meetmephi"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=meetmephi
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  backend:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    container_name: backend
    ports:
      - '8000:8000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/meetmephi
      - JWT_KEY=sdmfkgmdfogmdfdfivmfdpivpdfvdf

