spring:
  application:
    name: MeetMephi
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://localhost:3310/meetmephi"
    username: root
    password: password
  jpa:
    generate-ddl: true
  security:
    user:
      name: Nastya
      password: meowhihi

server:
  port: 8000