spring:
  application:
    name: MeetMephi
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://127.0.0.1:3310/meetmephi"
    username: root
    password: password
  jpa:
    generate-ddl: true
server:
  port: 8000