spring:
  application:
    name: MeetMephi
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://localhost:3306/meetmephi"
    username: root
    password: password
  jpa:
    generate-ddl: true
  jwt:
    key: ${JWT_KEY}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000


server:
  port: 8000